services:
  - name: faculty-reporting-api
    type: web
    env: node
    plan: free
    region: oregon
    repo: https://github.com/TJustice785/faculty-reporting-system
    branch: main
    autoDeploy: true
    buildCommand: ""
    startCommand: node server.js
    healthCheckPath: /api/health
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: https://mainproject.com
      - key: JWT_SECRET
        generateValue: true
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: UPLOAD_PATH
        value: ./uploads
      - key: DATABASE_URL
        fromDatabase:
          name: faculty-reporting-db
          property: connectionString

databases:
  - name: faculty-reporting-db
    plan: free
    region: oregon
